#Gerador de historia

game.splash("Um jovem ninja treinando","Para ser o melhor",)
# Uma jornada
game.splash("Uma jornada")
ninja = sprites.create(img("""
    ........................
    .......fff..............
    ....fffff2f.............
    ..ffeeeee22ff...........
    .ffeeeeee222ff..........
    .feeeefffeeeef..........
    .fffffeee2222ef.........
    fffe222fffffe2f.........
    fffffffffeeefff.....cc..
    fefe44ebbf44eef...ccdc..
    .fee4d4bbfddef..ccddcc..
    ..feee4dddddfeecdddc....
    ...f2222222eeddcdcc.....
    ...f444445e44ddccc......
    ...ffffffffeeee.........
    ...fff...ff.............
    ........................
    ........................
    ........................
    ........................
    ........................
    ........................
    ........................
    ........................
"""), SpriteKind.player)

ninja.set_position(10, 65)
mestre = sprites.create(img("""
. . . . f f f f f f . . . . . .
. . . f 2 f 2 2 2 2 f f . . . .
. . f 2 2 2 f 2 2 2 2 f f . . .
. . f 2 2 2 2 f f 2 2 2 f . . .
. f 2 2 2 2 2 2 2 f f f f . . .
. f 2 2 f f f f 2 2 2 2 f . . .
. f f f e e e f f f f f f f . .
. f e e d d 3 d e d d e f f . .
. . f e d d 3 1 1 d d e e f . .
. . . f 1 1 1 1 1 e e e f . . .
. . . f 1 1 1 4 e e f f . . . .
. . . f 1 1 1 e d d 4 . . . . .
. . . f 2 2 2 e d d e . . . . .
. . . f 5 5 4 f e e f . . . . .
. . . . f f f f f f . . . . . .
. . . . . . e e e . . . . . . .
"""), SpriteKind.player)

ninja.set_position(10, 65)
game.show_long_text("Eu vou ser o melhor !", DialogLayout.BOTTOM)
game.show_long_text("Você vai ser !", DialogLayout.BOTTOM)
game.show_long_text("Obrigado mestre !", DialogLayout.BOTTOM)
game.show_long_text("Vou treinar", DialogLayout.BOTTOM)
game.splash("Vá, Agora !")